[package]
name = "superZenBreakoutBevy"
version = "0.1.0"
authors = ["thegrimderp <admin@superzen.org>"]
edition = "2022"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5"
